default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: solo_development

test:
  <<: *default
  database: solo_test

production:
  <<: *default
  database: solo_production
  username: solo
  password: <%= ENV['LENTA_DATABASE_PASSWORD'] %>
